[package]
name = "backgammon"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.7.11"
borsh = "0.9.1"
thiserror = "1.0.24"
solana-frozen-abi = "1.7.11"
zeroize = "=1.3.0"

[lib]
crate-type = ["cdylib", "lib"]
